runtime: custom
env: flex

service: default

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

env_variables:
  GOOGLE_CLOUD_PROJECT: "still-catwalk-441910-u6"
  CLOUD_STORAGE_BUCKET: "video-subtitles-storage-xyz"

# Référence au secret
includes:
  - env_secrets.yaml

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT app:app

inbound_services:
- warmup