runtime: python39
instance_class: F2

env_variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10 