runtime: python39
instance_class: F1

env_variables:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  CLOUD_STORAGE_BUCKET: "video-subtitles-storage-xyz"

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  target_throughput_utilization: 0.6

inbound_services:
- warmup

basic_scaling:
  max_instances: 5
  idle_timeout: 10m