runtime: python39
instance_class: F1

env_variables:
  CLOUD_STORAGE_BUCKET: "video-subtitles-storage-xyz"

# Référence au secret
includes:
  - env_secrets.yaml

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  target_throughput_utilization: 0.6

inbound_services:
- warmup